// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXc069MFVzy5sfPItKfGGlHRuGEMQA21w',
    appId: '1:906329498083:web:dd61bf6bae73814ce980d6',
    messagingSenderId: '906329498083',
    projectId: 'login-firebase-93ca0',
    authDomain: 'login-firebase-93ca0.firebaseapp.com',
    databaseURL: 'https://login-firebase-93ca0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-firebase-93ca0.appspot.com',
    measurementId: 'G-CEXYX287HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6QO5m2B8iwc5WloKnLiJTTiTYuTSKoUo',
    appId: '1:906329498083:android:23a20b6e4fa0a366e980d6',
    messagingSenderId: '906329498083',
    projectId: 'login-firebase-93ca0',
    databaseURL: 'https://login-firebase-93ca0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-firebase-93ca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCtg8yn_xpWAF34TqgS8ERCaCLY4SIu1g',
    appId: '1:906329498083:ios:b9d3adb224e3a300e980d6',
    messagingSenderId: '906329498083',
    projectId: 'login-firebase-93ca0',
    databaseURL: 'https://login-firebase-93ca0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-firebase-93ca0.appspot.com',
    iosClientId: '906329498083-orn2eksc8habcgjcsmg7ani580nvijcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCtg8yn_xpWAF34TqgS8ERCaCLY4SIu1g',
    appId: '1:906329498083:ios:b9d3adb224e3a300e980d6',
    messagingSenderId: '906329498083',
    projectId: 'login-firebase-93ca0',
    databaseURL: 'https://login-firebase-93ca0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-firebase-93ca0.appspot.com',
    iosClientId: '906329498083-orn2eksc8habcgjcsmg7ani580nvijcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebase',
  );
}
